 const translations = {
      pt: {
        Configstitle:"Configurações",
        idioma:"Idioma",
        title3:"Visualizador do NEO da NASA",
        dias7:"Objetos próximos à Terra(Próximos 7 dias)",
        Nome:"Nome",
        Diametro:"Diâmetro(m)",
        Velocidade:"Velocidade(m/s)",
        DistanciaDeErro:"Distância de Erro(km)",
        Perigo:"Perigo",
        Dia:"Data de Aproximação",
        loading:"Carregando...",
        title2:"Simulador de defesa de meteoros",
        Clica:"Clique no mapa para lançar o meteoro",
        Vel:"Velocidade(m/s)",
        diam:"Diâmetro(m)",
        dens:"Densidade(kg/m³)",
        DefenseMode:"Método de Defesa",
        nada:"Nenhum(Impacto Direto)",
        bombaatomica:"Explosão Nuclear",
        kinetic:"Impactador Cinético",
        trator:"Trator Gravitacional",
        laser:"Laser Espacial",
        bombadesatomica:"Perfuração Explosiva",
        atmosfera:"Defesa Atmosférica",
        Ativar:"Ativar o Lançamento",
        title:"Página Inicial",
        button:"Simulador de defesa de meteoros",
        button1:"Base de dados do NEO",
        button2:"Configurações",
        button5:"Voltar",
        butao3:"Simulador de Defesa de Meteoro"
      },
      en: {
        Configstitle:"Assets",
        idioma:"Language",
        title3:"NASA NEO's Viewer",
        dias7:"Near-Earth Objects (Next 7 Days)",
        Nome:"Name",
        Diametro:"Diameter(m)",
        Velocidade:"Velocity(m/s)",
        DistanciaDeErro:"Miss Distance(km)",
        Perigo:"Hazardous",
        Dia:"Close Approach Date",
        loading:"Loading...",
        title2:"Meteor Defense Simulator",
        Clica:"Click on the map to launch the meteor",
        Vel:"Velocity(m/s)",
        diam:"Diameter(m)",
        dens:"Density(kg/m³)",
        DefenseMode:"Defense Method",
        nada:"None (Direct Impact)",
        bombaatomica:"Nuclear Explosion",
        kinetic:"Kinetic Impactor",
        trator:"Gravity Tractor",
        laser:"Space Laser",
        bombadesatomica:"Drilling Explosion",
        atmosfera:"Atmospheric Defense",
        title:"Starting page",
        button:"Meteor Defense Simulator",
        button1:"NEO's database",
        button2:"Settings",
        button5:"Back",
        butao3:"Meteor Defense Simulator"
      },
      es: {
        Configstitle:"Configuraciones",
        idioma:"Idioma",
        title3:"Visualizador del NEO de NASA",
        dias7:"Objeto próximos a la Tierra (Próximos 7 dias)",
        Nome:"Nombre",
        Diametro:"Diametro(m)",
        Velocidade:"Velocidad(m/s)",
        DistanciaDeErro:"Distancia de Error(km)",
        Perigo:"Peligro",
        Dia:"Fecha de aproximación terrestre",
        loading:"Cargando...",
        title2:"Simulador de Defensa de Meteoros",
        Clica:"Haga clic en el mapa para lanzar el meteoro",
        Vel:"Velocidad(m/s)",
        diam:"Diametro(m)",
        dens:"Densidad(kg/m³)",
        DefenseMode:"Metodo de Defensa",
        nada:"Ninguno(Impacto Directo",
        bombaatomica:"Explosión Nuclear",
        kinetic:"Impactador Cinético",
        trator:"Tractor Gravitacional",
        laser:"Laser Espacial",
        bombadesatomica:"Explosión de perforación",
        atmosfera:"Defensa Atmosférica",
        title:"Página Inicial",
        button:"Simulador de Defensa de Meteoro",
        button1:"Base de Dados de NEO",
        button2:"Configuraciónes",
        button5:"Volver"
      }
    };

    const select = document.getElementById("languageSwitcher");
    const elements = document.querySelectorAll("[data-translate]");

    select.addEventListener("change", () => {
      const lang = select.value;
      elements.forEach(el => {
        const key = el.getAttribute("data-translate");
        el.textContent = translations[lang][key];
      });
    });